name: dishinapp
description: A homecook application
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^1.1.1
  faker: ^1.2.1
  modal_bottom_sheet: ^0.2.2
  loading_overlay: ^0.2.1
  flutter_spinkit: ^4.1.2+1
  adaptive_dialog: ^0.9.0
  validators: ^2.0.1
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/